// LOCAL
### GET home
GET http://localhost:3001

### GET all movies
GET http://localhost:3001/movies

### GET specific movie
GET http://localhost:3001/movies/<any>
### Add movie (POST)
POST http://localhost:3001/movies
Content-Type: application/json

{ 
    "Name": "any",
    "Description": "any",
    "Director": "any",
    "DistributedBy": "any",
    "ProductionCompany": "any",
    "Cinematography": "any",
    "BoxOffice": "any",
    "ReleaseDate": "any",
    "MusicBy": "any"
}

### Update movie (PUT)
PUT http://localhost:3001/movies/<any>
Content-Type: application/json

{ 
    "Name": "any",
    "Description": "any",
    "Director": "any",
    "DistributedBy": "any",
    "ProductionCompany": "any",
    "Cinematography": "any",
    "BoxOffice": "any",
    "ReleaseDate": "any",
    "MusicBy": "any"
}

### Delete movie
DELETE http://localhost:3001/movies/<any>

// PRODUCTION
### GET home
GET https://cse341bh-project2.onrender.com

### GET all movies
GET https://cse341bh-project2.onrender.com/movies

### GET specific movie
GET https://cse341bh-project2.onrender.com/movies/<any>

### Add movie (POST movie)
POST https://cse341bh-project2.onrender.com/movies
Content-Type: application/json

{ 
    "Name": "any",
    "Description": "any",
    "Director": "any",
    "DistributedBy": "any",
    "ProductionCompany": "any",
    "Cinematography": "any",
    "BoxOffice": "any",
    "ReleaseDate": "any",
    "MusicBy": "any"
}

### Change movie information (PUT)
PUT https://cse341bh-project2.onrender.com/movies/<any>
Content-Type: application/json

{ 
    "Name": "any",
    "Description": "any",
    "Director": "any",
    "DistributedBy": "any",
    "ProductionCompany": "any",
    "Cinematography": "any",
    "BoxOffice": "any",
    "ReleaseDate": "any",
    "MusicBy": "any"
}

### Remove a movie (DELETE)
DELETE https://cse341bh-project2.onrender.com/movies/<any>
